apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: mytanzuwebapp.mydevns.tap.20230714113334.0.0+build.13e7965
spec:
  refName: mytanzuwebapp.mydevns.tap
  version: 20230714113334.0.0+build.13e7965
  releaseNotes: |
    Release v20230714113334.0.0+build.13e7965 of package mytanzuwebapp.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/mytanzuwebapp-mydevns-bundle@sha256:dce25cd9e173e52fc7b88dc8a43fa4bddc27caab5fcc1677103d7de8d1908e52
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 2
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned
        greeting:
          title: Greeting
          type: string
          description: Parameter to greeting
          default: from-outer-space

