apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-source-java-hello.mydevns.tap.20230713171940.0.0+build.5155d72
spec:
  refName: server-source-java-hello.mydevns.tap
  version: 20230713171940.0.0+build.5155d72
  releaseNotes: |
    Release v20230713171940.0.0+build.5155d72 of package server-source-java-hello.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-source-java-hello-mydevns-bundle@sha256:b53a3125b0fc8646db008f2f4e9792208202ea5fd9a944f833c43b6234aa529c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 10
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned

