apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-source-java-hello.mydevns.tap.20230718154908.0.0+build.5653e6f
spec:
  refName: server-source-java-hello.mydevns.tap
  version: 20230718154908.0.0+build.5653e6f
  releaseNotes: |
    Release v20230718154908.0.0+build.5653e6f of package server-source-java-hello.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-source-java-hello-mydevns-bundle@sha256:b0159867e9f4b1fcf32c6005c172b37235ff2181d42e863ea95a361f50265870
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 3
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned
        greeting:
          title: Greeting
          type: string
          description: Parameter to greeting
          default: from-outer-space-hahahaha

