apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-source-url-after-params-set-2.mydevns.tap.20230713035619.0.0+build.5155d72
spec:
  refName: server-source-url-after-params-set-2.mydevns.tap
  version: 20230713035619.0.0+build.5155d72
  releaseNotes: |
    Release v20230713035619.0.0+build.5155d72 of package server-source-url-after-params-set-2.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-source-url-after-params-set-2-mydevns-bundle@sha256:f56355f258b3fbd3ad6369306f96891a39012f7270997525b443b23561e57ee5
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 21
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned

