apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-source-url.mydevns.tap.20230712130208.0.0+build.b470251
spec:
  refName: server-source-url.mydevns.tap
  version: 20230712130208.0.0+build.b470251
  releaseNotes: |
    Release v20230712130208.0.0+build.b470251 of package server-source-url.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-source-url-mydevns-bundle@sha256:66ab93950707e2119fed17723928e70774c901a7e62788277b641900eea0f88b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 11

