apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: web-img-to-url.mydevns.tap.20230714031949.0.0
spec:
  refName: web-img-to-url.mydevns.tap
  version: 20230714031949.0.0
  releaseNotes: |
    Release v20230714031949.0.0 of package web-img-to-url.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/web-img-to-url-mydevns-bundle@sha256:2bc4c5e429879018ee653b867ce34677bd895776fd5a3e7ea7a0e20b4f6f05ea
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

