---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: server-source-java-hello.mydevns.tap
spec:
 serviceAccountName: default
 packageRef:
   refName:  server-source-java-hello.mydevns.tap
   versionSelection:
     constraints: ">=0.0.0" 
 values:
 - secretRef:
     name: server-source-java-hello-mydevns-tap