apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-img-server.mydevns.tap.20230626133114.0.0
spec:
  refName: tanzu-java-web-app-img-server.mydevns.tap
  version: 20230626133114.0.0
  releaseNotes: |
    Release v20230626133114.0.0 of package tanzu-java-web-app-img-server.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/tanzu-java-web-app-img-server-mydevns-bundle@sha256:2a727c9b506ca09c8e92534789b857a38b8c07022283f63433b73fb801eb7979
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

