apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-newparam.mydevns.tap.20230718155812.0.0+build.5653e6f
spec:
  refName: server-newparam.mydevns.tap
  version: 20230718155812.0.0+build.5653e6f
  releaseNotes: |
    Release v20230718155812.0.0+build.5653e6f of package server-newparam.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-newparam-mydevns-bundle@sha256:09f408ac1ba38a98e5ed894605fb47d0dda6a5c5ea14eb787a09860e0a1ca588
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 2
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned
        greeting:
          title: Greeting
          type: string
          description: Parameter to greeting
          default: from-outer-space-hahahaha

