---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: myservergitrepo3.mydevns.tap
 annotations:
    packaging.carvel.dev/downgradable: ""
spec:
 #serviceAccountName: <run-cluster-ns-sa> # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 serviceAccountName: default
 packageRef:
   #refName: app.default.tap # name of the Package
   refName: myservergitrepo3.mydevns.tap
   versionSelection:
     #constraints: 20230630200348.0.0 # version of the Package
     constraints: ">0.0.0-0" #20230630200348.0.0
 values:
 - secretRef:
     #name: app-values # Secret created in previous step
     name: my-gitreposecret
