---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: pkginstalljavaserverapp
spec:
 #serviceAccountName: <run-cluster-ns-sa> # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 serviceAccountName: default
 packageRef:
   #refName: app.default.tap # name of the Package
   refName: tanzu-java-web-app-img-server.mydevns.tap #.20230626133114.0.0
   versionSelection:
     #constraints: 20230321004057.0.0 # version of the Package
     constraints: 20230626133114.0.0
 values:
 - secretRef:
     #name: app-values # Secret created in previous step
     name: my-java-serverapp-mydevns-tap
