apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: server-source-url-after-params-set.mydevns.tap.20230712192500.0.0+build.5155d72
spec:
  refName: server-source-url-after-params-set.mydevns.tap
  version: 20230712192500.0.0+build.5155d72
  releaseNotes: |
    Release v20230712192500.0.0+build.5155d72 of package server-source-url-after-params-set.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/server-source-url-after-params-set-mydevns-bundle@sha256:8e9e54adb56a5113a8c131652c099e6aa69e4b7300fada2843b1eec1f0746e7e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 7
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned
        target:
          title: target
          type: string
          description: param to hello
          default: from-outer-space

