---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: img-to-url.mydevns.tap #name of package without the version 
spec:
 #serviceAccountName: <run-cluster-ns-sa> # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 serviceAccountName: default
 packageRef:
   #refName: app.default.tap # name of the Package
   refName: img-to-url.mydevns.tap #pkg name without version
   versionSelection:
     #constraints: 20230321004057.0.0 # version of the Package
     constraints: 20230711152501.0.0
 values:
 - secretRef:
     #name: app-values # Secret created in previous step
     name: my-img-to-url-secret