---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: server-source-url-after-params-set-2.mydevns.tap
spec:
 serviceAccountName: default
 packageRef:
   refName:  server-source-url-after-params-set-2.mydevns.tap
   versionSelection:
     # constraints: 20230712142555.0.0+build.b470251 #">=0.0.0"
     constraints: 20230712145511.0.0+build.b470251
 values:
 - secretRef:
     name: server-source-url-after-params-set-2-mydevns-tap
