---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: mytanzuwebapp-params.mydevns.tap
spec:
 #serviceAccountName: <run-cluster-ns-sa> # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 serviceAccountName: default
 packageRef:
   #refName: app.default.tap # name of the Package
   refName: mytanzuwebapp-params.mydevns.tap 
   versionSelection:
     constraints: ">=0.0.0"
 values:
 - secretRef:
     name: mytanzuwebapp-params.mydevns.tap
